### PR TITLE
[#25] Otp 18 errors

### PR DESCRIPTION
**Pull request by jfacorro**
#25

### CODE REVIEW

**Comment by fenollp** [comment]
Hey @jfacorro. Thanks for taking the time of contributing your code to the community!

I have a couple notes:
1. Why push a custom `docgen_edoc_xml_cb` module when one is provided *and maintained* by the OTP team? Is there something hidden inside that is useful? If yes please be explicit about it.
2. Why update `specs_gen__R15_and_above`? I would have just added a `specs_gen__18_and_above` and [added a clause to use this module](https://github.com/jfacorro/erldocs/blob/8261eba2e67b46527d8b9b0fb4fdc8b9576d201d/src/erldocs_core.erl#L141). `specs_gen__18_and_above` would come from [latest OTP](https://github.com/erlang/otp/blob/maint/lib/erl_docgen/priv/bin/specs_gen.escript).

Please get back to me

**Comment by jfacorro** [comment]
@fenollp Thanks for your comments.

1. When the `docgen_edoc_xml_cb` module is used the processing of the specs' XML generates an error since there are a few cases that are not currently being handled. These are: elements with name [`paren`](https://github.com/erldocs/erldocs/pull/31/files#diff-dc217f8bca77391904b8df10372d80ebR1034) and when a node has [two children](https://github.com/erldocs/erldocs/pull/31/files#diff-dc217f8bca77391904b8df10372d80ebR1036) as part of its content. 
2. I agree adding a new module for 18 and above is a better approach :smile:.

I just pushed the modifications. Please let me know if you need me to do any further changes.

**Comment by jfacorro** [comment]
@fenollp After some testing I found that replacing `docgen_edoc_xml_cb` for the custom one was introducing some bugs. I removed it but the issue remains regarding the `docgen_edoc_xml_cb` not being able to handle some of the `xmlElements` that `t_type` receives as arguments. I guess a PR to `otp` to fix this is more appropriate than trying to patch it in erldocs :stuck_out_tongue:.

**Comment by fenollp** [comment]
@jfacorro Ah! I'm glad you properly understood my motivation for not maintaining a custom `docgen_edoc_xml_cb` module.

Amazing! Well, report the bug to the OTP team (they have a proper open bug tracker now) and maybe fix it yourself over there :).
Note that their documentation also has some bugs too (take a look at the daily-generated logs for the maint branch on erldocs.com)

**Comment by fenollp** [comment]
For the record: "specs18" file came from https://github.com/erlang/otp/blob/738c34d4bb8f1a3811acd00af8c6c12107f8315b/lib/erl_docgen/priv/bin/specs_gen.escript

**Comment by fenollp** [comment]
Tonight's staging (on 18.1) [was interesting](https://github.com/erldocs/erldocs.com/commit/6b0193857a62a5638fb63ae76a98b8a024d469e8) @jfacorro :)

**Pull request merged**
