### PR TITLE
bug #51 make charset in erldocs.dtl match bytes written to file

### PR DESCRIPTION
**Pull request by jesperes**
The actual bytes written using the `erldocs.dtl` are latin-1, not utf8, so make `<meta charset=.../>` match that. This should fix the problem with "funny characters" being displayed.

### CODE REVIEW

**Comment by jesperes** [comment]
I'm unsure what's happening with the broken build. I cannot reproduce it locally, and seems unrelated to this change.

**Comment by fenollp** [comment]
Thanks for takig a look at this!
Yeah one of the builds fails because this PR only modifies generated HTML. This doesn't fix anything really. 
Instead this needs to be an Erlang code fix that tried to convert latin1 source docs into utf-8 before the call to edoc.

**Comment by fenollp** [comment]
Hey @jesperes do you mind rebasing this?

**Comment by fenollp** [comment]
Superseeded by https://github.com/erldocs/erldocs/pull/76

**Pull request closed without merging**
